In [6]:
import pandas as pd
import numpy as np
from datetime import timedelta, datetime
import matplotlib.pyplot as plt
from nemosis import static_table, dynamic_data_compiler, defaults
import plotly.express as px
import nem_bidding_dashboard

raw_data_cache = '/Volumes/T7/NEMO_data'

pd.set_option('display.max_columns', None)

In [5]:
volume_bids = dynamic_data_compiler(start_time='2015/01/01 00:00:00',
                                    end_time='2016/06/01 00:00:00',
                                    table_name='BIDPEROFFER_D',
                                    raw_data_location=raw_data_cache)

INFO: Compiling data for table BIDPEROFFER_D
INFO: Returning BIDPEROFFER_D.

In [4]:
volume_bids

,SETTLEMENTDATE,DUID,BIDTYPE,OFFERDATE,MAXAVAIL,ENABLEMENTMIN,ENABLEMENTMAX,LOWBREAKPOINT,HIGHBREAKPOINT,BANDAVAIL1,BANDAVAIL2,BANDAVAIL3,BANDAVAIL4,BANDAVAIL5,BANDAVAIL6,BANDAVAIL7,BANDAVAIL8,BANDAVAIL9,BANDAVAIL10,INTERVAL_DATETIME
0,2016-01-31,APD01,LOWER5MIN,2002-10-17 08:51:56,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,300,2016-01-31 04:30:00
1,2016-01-31,APD01,LOWER5MIN,2002-10-17 08:51:56,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,300,2016-01-31 04:25:00
2,2016-01-31,APD01,LOWER5MIN,2002-10-17 08:51:56,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,300,2016-01-31 04:20:00
3,2016-01-31,APD01,LOWER5MIN,2002-10-17 08:51:56,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,300,2016-01-31 04:15:00
4,2016-01-31,APD01,LOWER5MIN,2002-10-17 08:51:56,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,300,2016-01-31 04:10:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8393874,2016-01-31,APD01,RAISE60SEC,2016-01-31 23:37:34,446,0.0,0.0,0.0,0.0,5,0,0,0,0,0,5,5,0,465,2016-01-31 23:45:00
8393923,2016-01-31,APD01,RAISE6SEC,2016-01-31 23:37:34,446,0.0,0.0,0.0,0.0,3,0,0,0,0,0,5,5,0,467,2016-02-01 00:00:00
8393924,2016-01-31,APD01,RAISE6SEC,2016-01-31 23:37:34,446,0.0,0.0,0.0,0.0,3,0,0,0,0,0,5,5,0,467,2016-01-31 23:55:00
8393925,2016-01-31,APD01,RAISE6SEC,2016-01-31 23:37:34,446,0.0,0.0,0.0,0.0,3,0,0,0,0,0,5,5,0,467,2016-01-31 23:50:00
8393926,2016-01-31,APD01,RAISE6SEC,2016-01-31 23:37:34,446,0.0,0.0,0.0,0.0,3,0,0,0,0,0,5,5,0,467,2016-01-31 23:45:00

In [ ]:
# Define the file path
file_path = '/Users/danielseymour/Downloads/AER_FCAS_Quarterly global FCAS price by services DATA_2_20241127112059.CSV'

# Load the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
df.head()

In [ ]:

# Set figure size
plt.figure(figsize=(12, 6))

# Plot the average Raise and Lower Regulation FCAS prices
plt.plot(df['Quarter'], df['AVG_RAISEREG ($ per megawatt)'], label="Avg Raise Regulation", linestyle='-', marker='o', markersize=5)
plt.plot(df['Quarter'], df['AVG_LOWERREG ($ per megawatt)'], label="Avg Lower Regulation", linestyle='-', marker='x', markersize=5)

# Formatting the plot
plt.xlabel("Year-Quarter")
plt.ylabel("Price ($ per MW)")
plt.title("Quarterly Average of Raise & Lower Regulation FCAS Prices from 2010 Q1 - 2024 Q3")
plt.legend()
plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.grid(True, linestyle='--', alpha=0.7)

# Show the plot
plt.show()

In [ ]:
# Get the price bids.
price_data = dynamic_data_compiler(start_time='2010/01/19 00:00:00',
                                   end_time='2024/09/01 00:00:00',
                                   table_name='DISPATCHPRICE',
                                   raw_data_location=raw_data_cache,
                                   rebuild=True)

In [ ]:
price_data

In [ ]:
price_data.describe()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Ensure the 'SETTLEMENTDATE' column is in datetime format
price_data['SETTLEMENTDATE'] = pd.to_datetime(price_data['SETTLEMENTDATE'])

# Resample the data to monthly averages for better visualization
df_resampled = price_data.set_index('SETTLEMENTDATE').resample('M').mean()

# Set figure size
plt.figure(figsize=(14, 7))

# Plot each FCAS category over time
plt.plot(df_resampled.index, df_resampled['RRP'], label="Regional Reference Price (RRP)", linestyle='-', marker='.')
plt.plot(df_resampled.index, df_resampled['RAISE6SECRRP'], label="Raise 6-Sec", linestyle='-', marker='.')
plt.plot(df_resampled.index, df_resampled['RAISE60SECRRP'], label="Raise 60-Sec", linestyle='-', marker='.')
plt.plot(df_resampled.index, df_resampled['RAISE5MINRRP'], label="Raise 5-Min", linestyle='-', marker='.')
plt.plot(df_resampled.index, df_resampled['RAISEREGRRP'], label="Raise Regulation", linestyle='-', marker='.')
plt.plot(df_resampled.index, df_resampled['LOWER6SECRRP'], label="Lower 6-Sec", linestyle='-', marker='.')
plt.plot(df_resampled.index, df_resampled['LOWER60SECRRP'], label="Lower 60-Sec", linestyle='-', marker='.')
plt.plot(df_resampled.index, df_resampled['LOWER5MINRRP'], label="Lower 5-Min", linestyle='-', marker='.')
plt.plot(df_resampled.index, df_resampled['LOWERREGRRP'], label="Lower Regulation", linestyle='-', marker='.')

# Formatting the plot
plt.xlabel("Time (Months)")
plt.ylabel("Price ($ per MW)")
plt.title("FCAS Prices Over Time (Resampled Monthly)")
plt.legend()
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.7)

# Show the plot
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Ensure the 'SETTLEMENTDATE' column is in datetime format
price_data['SETTLEMENTDATE'] = pd.to_datetime(price_data['SETTLEMENTDATE'])

# Resample the data to monthly averages for better visualization
df_resampled = price_data.set_index('SETTLEMENTDATE').resample('M').mean()

# Set figure size
plt.figure(figsize=(14, 7))

# Plot each FCAS category over time
plt.plot(df_resampled.index, df_resampled['RAISEREGRRP'], label="Raise Regulation", linestyle='-', marker='.')
plt.plot(df_resampled.index, df_resampled['LOWERREGRRP'], label="Lower Regulation", linestyle='-', marker='.')

# Formatting the plot
plt.xlabel("Time (Months)")
plt.ylabel("Price ($ per MW)")
plt.title("FCAS Prices Over Time (Resampled Monthly)")
plt.legend()
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.7)

# Show the plot
plt.show()

In [ ]:
volume_bids

In [ ]:
# This is the table showing what electricity has been actually dispatched
# Used to find the inelastic demand in each region
dispatch_load_df = dynamic_data_compiler(start_time='2024/03/01 00:00:00',
                                   end_time='2024/04/10 00:00:00',
                                   table_name='DISPATCHLOAD',
                                   raw_data_location=raw_data_cache, 
                                   rebuild=True)
dispatch_load_df

Is there a simple way to calculate payments for 
If it's roughly based on marginal cost pricing, even if there are often more complicated factors, and it's completely orthogonal to standard energy dispatch, then surely I can multiply the amount each firm dispatched by the clearing price to get an estimate. Later, I can add a confidence interval in the knowledge that there is more complexity around the price the firm actually recieves.

In [ ]:
dispatch_load_df

In [ ]:
fcas = dynamic_data_compiler(start_time='2025/01/01 00:00:00',
                                   end_time='2025/01/02 00:00:00',
                                   table_name='FCAS_4_SECOND',
                                   raw_data_location=raw_data_cache)
fcas

In [ ]:
fcas

In [ ]:
# Required to join DUIDs to firm names 
ELEMENTS_FCAS_4_SECOND = static_table(table_name='ELEMENTS_FCAS_4_SECOND', 
                              raw_data_location=raw_data_cache,
                              update_static_file=False)
ELEMENTS_FCAS_4_SECOND

In [ ]:
VARIABLES_FCAS_4_SECOND = static_table(table_name='VARIABLES_FCAS_4_SECOND', 
                              raw_data_location=raw_data_cache,
                              update_static_file=False)

VARIABLES_FCAS_4_SECOND

In [ ]:
defaults.table_columns['TRADINGPRICE'] += ['RAISE1SECRRP', 'RAISE1SECROP', 'LOWER1SECRRP', 'LOWER1SECROP']

In [ ]:
print(defaults.table_columns.get('DISPATCHPRICE'))

In [ ]:
# Get the price bids.
trading_price_df = dynamic_data_compiler(start_time='2023/10/09 00:00:00',
                                   end_time='2025/02/20 00:00:00',
                                   table_name='TRADINGPRICE',
                                   raw_data_location=raw_data_cache,
                                   rebuild=True)

In [ ]:
trading_price_df

In [ ]:
trading_price_df.describe()

In [ ]:
# Convert SETTLEMENTDATE to datetime format for proper plotting
trading_price_df['SETTLEMENTDATE'] = pd.to_datetime(trading_price_df['SETTLEMENTDATE'])

# Set figure size
plt.figure(figsize=(12, 6))

# Plot the RAISE1SECRRP and LOWER1SECRRP over time
plt.plot(trading_price_df['SETTLEMENTDATE'], trading_price_df['RAISE1SECRRP'], label="Raise 1 Sec RRP", linestyle='-', marker='o', markersize=4)
plt.plot(trading_price_df['SETTLEMENTDATE'], trading_price_df['LOWER1SECRRP'], label="Lower 1 Sec RRP", linestyle='-', marker='x', markersize=4)

# Formatting the plot
plt.xlabel("Settlement Date")
plt.ylabel("Price ($/MWh)")
plt.title("Raise & Lower 1-Second FCAS Prices Over Time")
plt.legend()
plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.grid(True, linestyle='--', alpha=0.7)

# Show the plot
plt.show()